[package]
name = "guid-parser"
version = "0.1.0"
authors = ["David Herman <david.herman@gmail.com>"]
repository = "https://github.com/dherman/guid"
license = "MIT/Apache-2.0"

[dependencies]
chomp = "0.3.1"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
